import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "TEFA SMK Telkom Malang",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo-SMK Telkom.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${plusJakartaSans.variable} h-full antialiased`}
    >
      <head>
        <style>{`
          :root { --background: #ffffff; --foreground: #171717; --primary: #e63946; --primary-hover: #c1121f; }
          html, body { margin: 0; padding: 0; box-sizing: border-box; overflow-x: hidden; }
          body { background: var(--background); color: var(--foreground); font-family: var(--font-plus-jakarta-sans), sans-serif; }
          * { box-sizing: border-box; }
        `}</style>
      </head>
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
